#include <stdio.h>
#include <stdlib.h>
#include <math.h>




float movingAvg(int *ptrArrNumbers, long *ptrSum, int position, int length, int nextNumber)
{
  *ptrSum = *ptrSum - ptrArrNumbers[position] + nextNumber;	//Subtract the oldest number from the prev sum, add the new number
  
  ptrArrNumbers[position] = nextNumber;		//Assign the nextNumber to the position in the array
 
  return *ptrSum / length;		//return the average
}





void main(int argc, char** argv)
{
  // open the noisy sin wave 
  FILE * input_file;
  input_file = fopen(argv[1],"r");  



  float a; int i=0; int c=0;
  



  if(input_file !=NULL)   //works if its open
  {
    while(fscanf(input_file,"%f",&a)!=EOF)    //counts how much memory needed 
    {
      ++i;
    }
  }

  printf("the number of i is %d\n",i);     //just to make sure the count is correct 


  rewind (input_file);    //closes the inputfile 

  int x[] = {i};   //sets x to the numbers generated by the noisy sin wave 


  for(c=0;c<i;c++)
  {
    fscanf(input_file,"%f",&x[c]);    //sets x to the numer line by line 

  }



  // the size of this array represents how many numbers will be used to calculate the average

  int arrNumbers[5] = {0};
  

  int position = 0;
  int newAvg = 0;
  long sum = 0;


  int length = sizeof(arrNumbers) / sizeof(int);
  int count = sizeof(x) / sizeof(int);


  for(int m = 0; m < count; m++)
  {

    newAvg = movingAvg(arrNumbers, &sum, position, length, x[m]);
    printf("average is %d\n", newAvg);
    position++;


    if (position >= length)
    {
      position = 0;
    }

  }

 //return 0;
}